[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::pydantic.PydanticDeprecatedSince20
    ignore::UserWarning
    ignore::FutureWarning
    ignore:.*urllib3.*
    ignore:.*tagMap.*
    ignore:.*typeMap.*
    ignore:.*phoenix.*
    ignore:.*strawberry.*
    ignore:.*alembic.*
    ignore:.*SAWarning.*
    ignore:.*Pydantic V1.*
    ignore:.*reflection.*
